### ISSUE TITLE
Possibly replace use of `styfle/cancel-workflow-action` with `cancel-in-progress`

### ISSUE THREAD

**Issue by stevenengler** [shadow/tornettools#115]
We have a github CI workflow to cancel a previously run 'run-all-steps' workflow. We use the third-party `styfle/cancel-workflow-action` action with `actions: write` permissions for this. But since then github has added a `cancel-in-progress` workflow option. We should possibly switch to this instead if it serves the same purpose.

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs

https://github.com/shadow/tornettools/blob/df6ada5e74c1eda22899610e4d1bed13a37878eb/.github/workflows/cancel_prev_run_all_steps.yml#L4-L11

**Comment by sporksmith** [comment]
Nice - yeah I think this is what we want

> For example, you can use the concurrency keyword immediately after where trigger conditions are defined to limit the concurrency of entire workflow runs for a specific branch:

```
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```
