### ISSUE TITLE
Can generate configs w multiple hosts with same IP address

### ISSUE THREAD

**Issue by sporksmith** [shadow/tornettools#38]
We can generate multiple relays with the same network node and ip address. Example:

```
  relay124exit:
    network_node_id: 914
    ip_addr: 194.5.249.130
    ...
  relay125exit:
    network_node_id: 914
    ip_addr: 194.5.249.130
```

@stevenengler says:

> Yep that looks like a bug in tornettools. I think it samples two different relays that have the same IP address and shadow doesn't support having two different hosts with the same IP address. Maybe when sampling relays if we already have a relay with that IP address, we should just increment the address (as an integer) by one until it's unused?

> okay, the sampling should be in __sample_relays() , and that eventually gets converted to the config format in __filter_nodes() , i think the fix will be somewhere in there (edited)

**Comment by sporksmith** [comment]
Using the same staging data, I reran `generate` and `simulate` and ended up getting a similar conflict. Given that I've never seen this otherwise, it seems like there's something special about the `generate` output that is causing this to happen. In both cases, the collision happens on "adjacent" relays. before relay124 and relay125, this time relay1exitguard and relay2exitguard:

```
  relay1exitguard:
    network_node_id: 1601
    ip_addr: 185.220.100.254
    ...
  relay2exitguard:
    network_node_id: 1601
    ip_addr: 185.220.100.254
    ...
```
